### ISSUE TITLE
Newer builds break Kid Icarus: Uprising bcres/bcmdl models.

### ISSUE THREAD

**Issue by robotortoise** [gdkchan/Ohana3DS-Rebirth#19]
I can't exactly tell when they stopped working, but they worked fine on version "o3ds_10_11_2015".

The models don't even load in the newer versions. I wonder why?

[palutena_kid_icarus_uprising.zip](https://github.com/gdkchan/Ohana3DS-Rebirth/files/128569/palutena_kid_icarus_uprising.zip)

Thank you for continuing to support Ohana3DS-Rebirth! This program is fantastic and I appreciate all the hard work you do, gdkchan!

**Comment by gdkchan** [comment]
It's working fine on my end, which error it gives to you?

**Comment by Demonslayerx8** [comment]
i actually get an error when opening texture files from Kid Icarus Uprising.

file at..
romfs > region > stage > g0101 > TEX00.bcres

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ohana3DS_Rebirth.Ohana.TextureCodec.etc1Decode(Byte[] input, Int32 width, Int32 height, Boolean alpha) in C:\Users\wolfs\Desktop\Ohana3DS-Rebirth-master\Ohana3DS Rebirth\Ohana\TextureCodec.cs:line 342
   at Ohana3DS_Rebirth.Ohana.TextureCodec.decode(Byte[] data, Int32 width, Int32 height, OTextureFormat format) in C:\Users\wolfs\Desktop\Ohana3DS-Rebirth-master\Ohana3DS Rebirth\Ohana\TextureCodec.cs:line 291
   at Ohana3DS_Rebirth.Ohana.Models.CGFX.load(Stream data) in C:\Users\wolfs\Desktop\Ohana3DS-Rebirth-master\Ohana3DS Rebirth\Ohana\Models\CGFX.cs:line 271
   at Ohana3DS_Rebirth.Ohana.FileIO.load(Stream data) in C:\Users\wolfs\Desktop\Ohana3DS-Rebirth-master\Ohana3DS Rebirth\Ohana\FileIO.cs:line 67
   at Ohana3DS_Rebirth.Ohana.FileIO.load(String fileName) in C:\Users\wolfs\Desktop\Ohana3DS-Rebirth-master\Ohana3DS Rebirth\Ohana\FileIO.cs:line 44
   at Ohana3DS_Rebirth.Ohana.FileIO.import(fileType type) in C:\Users\wolfs\Desktop\Ohana3DS-Rebirth-master\Ohana3DS Rebirth\Ohana\FileIO.cs:line 241
   at Ohana3DS_Rebirth.GUI.OTexturesPanel.BtnImport_Click(Object sender, EventArgs e) in C:\Users\wolfs\Desktop\Ohana3DS-Rebirth-master\Ohana3DS Rebirth\GUI\Panels\OTexturesPanel.cs:line 56
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by robotortoise** [comment]
Actually, the models seem to load fine on this revision. Guess I just had an older build.

But now the textures don't quite load properly. Though, it did that on the old revision, too.

For instance, take Palutena's model. This is what Ohana shows:

![palutena](https://cloud.githubusercontent.com/assets/7727806/13022752/aba96cb2-d1a0-11e5-8301-68c05f6173cb.png)


That's what Palutena looks like ingame: 
![scr_3_top_left](https://cloud.githubusercontent.com/assets/7727806/13023050/56bfc1fe-d1a2-11e5-9d1d-80a7f91b1158.png)
![scr_6_top_left](https://cloud.githubusercontent.com/assets/7727806/13023052/56c3243e-d1a2-11e5-819e-11b233d8c1f9.png)
![scr_7_top_right](https://cloud.githubusercontent.com/assets/7727806/13023051/56c1fdac-d1a2-11e5-9a38-dc842e3a0db5.png)

**Comment by Demonslayerx8** [comment]
enable fragment shader in Ohana and it'll show properly mate.

**Comment by gdkchan** [comment]
Like DSX8 said, enabling Fragment Shader will make it look better, althrough the fshader have problems of its own that I plan to fix sometime, not a priority since the fragment shader only affects what is viewed inside the tool anyway, what is exported will be still messed up (and I can't fix that).

I made a commit where I remove the DoEvents() logic and the hack to finish it without memory leaks (I think that this hack is what was causing the weird issues with models that worked fine not opening), it now uses a Timer instead... Well, accordingly to what I saw, it should have a precision of more or less 15ms, and I need ~16.67 to make it render at 60fps. I would be thankful if you guys can test the lastest commit and report if anything was broken from it, in particular if animations are slower or the UI is unresponsive.

**Comment by Demonslayerx8** [comment]
Tested the latest commit, and it gives me this error..

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileLoadException: Mixed mode assembly is built against version 'v1.1.4322' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration information.
   at Ohana3DS_Rebirth.GUI.OViewportPanel.Screen_MouseMove(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Also, been meaning to ask, whats the "Tools" tab gonna be used for? Can't click on it or anything, so im actually curious what its for :P 

Also, there's still some mbn models that doesnt keep their rig, can be seen with.. Prism Tower, and the Kirby stage from Smash3ds

**Comment by gdkchan** [comment]
@Demonslayerx8 Thanks for testing it, I think I will fallback to .net 3.5 to avoid those complications. About the Tools menu, it will be used to hold the "tools" that I plan to add, such as a bch mesh replacer and a texture replacer like the old Ohana3DS, and a tool do navigate through the model quickly, and maybe a batch exporter aswell.

**Comment by robotortoise** [comment]
So it doesn't look like Fshader is changing anything, but changing the "always use first texture" to "use last texture when present" seems to be fixing it a bit!

![2016-02-13 13_24_10-new notification](https://cloud.githubusercontent.com/assets/7727806/13029861/12fb90b6-d255-11e5-9cf2-823e9ac8507c.png)

**Comment by Demonslayerx8** [comment]
ehh? Fragment shader works fine for me...
![untitled](https://cloud.githubusercontent.com/assets/17195757/13031308/216f0abe-d27e-11e5-8afc-32bcdd18fb22.png)

**Comment by gdkchan** [comment]
Some users reporterd that the fragment shader was resulting in all-white models. I don't know what causes this issue, but I think that the problem lies on Managed DX, iirc I made a build long ago using SharpDX and the fragment shader worked. Anyway, its **impossible** to correctly blend the textures without a fragment shader due to the way the PICA200 works. The only possible solution I see on this case is either changing the lib, in hopes that the fshader starts working for everyone, but I really don't want to rewrite the RenderEngine at this point.

**Comment by robotortoise** [comment]
How the heck is it working for him?! I'm running Nvidia graphics on Windows 10, does that have something to do with it?

Anyways, it resulted in all-white models for me too, but it worked once I reset the model a few times.

**Comment by Demonslayerx8** [comment]
im using a AMD R7 260X Radeon GPU, so the fragment shader will probably ALWAYS work for AMD users... im not sure what GDKCHAN has.

**Comment by robotortoise** [comment]
Hm, maybe it's an Nvidia problem.

[I know I've seen a similar issue with the Majora's Mask 3D viewer.](https://github.com/xdanieldzd/N3DSCmbViewer)

Don't know if it was fixed, or how.

**Comment by Fallenleader** [comment]
honestly, I would rather see better format support (such as animations) and exporting support, than beautified viewing. Some people use the tool for data mining, which is the strong point or this tool.

**Comment by robotortoise** [comment]
I agree as well, Fallenleader.

...honestly if there were an option to "press F4 to restart the viewing engine" that'd probably fix the grey textures issue for now. It seems restarting the engine sometimes fixes it.

**Comment by Fallenleader** [comment]
Functionality before beautification is any programmers focus (or should be). Call of duty starts off as cylinders and cubes before becoming athe FPS we all know and love (or love to hate).

The focus should be the same here. Being able to see the model actually loads, or the textures can be read is more critical to the functionality of this tool than emulating what you see in game.

Not @gdkchan's fault, but we still don't have proper animation support for many major data mined games. A good example being Pokemon series (yes, I sound redundant, but I REALLY need those animations :P)

No one has figured out where the animations are for the in battle models for ORAS, I haven't found any proper support for X/Y in battle models (forget animations here, the whole format just became explorable after latest build), pokemon animations have yet to be RE'd to be supported here. I think that issues like these should be pointed out, but people should realize that the project is more towards viewing ALL 3DS formats, and being able to manipulate them, which means that things won't look pretty for now. Just my opinion though. My issues regarding the internals of the stuff is probably a big enough pain in the butt.

As mentioned @gdkchan , I agree with @robotortoise to add in a hotkey to reload the viewing screen since a reload fixes many of the minor issues here, with the major ones having been discussed and addressed.

**Comment by gdkchan** [comment]
I know that the "in-battle" models of Pokémon uses those blending effect to give a toon-shading like shadow to the characters. This effect isn't present on ohana3ds, and it's hard to notice since the model doesn't looks "wrong" without it.

**Comment by robotortoise** [comment]
Okay, I don't know about others, but I figured out the cause of the issue for me: f.lux, a program that alters screen brightness, was interfering and causing issue. It's not an Nvidia issue at all!

**Comment by Blayer98** [comment]
Oh interesting, I'll see if this fixes it for me, I also use that program
