### ISSUE TITLE
Texture colour errors...

### ISSUE THREAD

**Issue by Blayer98** [gdkchan/Ohana3DS-Rebirth#21]
![image](https://cloud.githubusercontent.com/assets/6663677/13268804/68fb6e9e-da7c-11e5-8226-83578fc56a87.png)

It appears that this character has some issues in regards to colours.

For example, they don't match the texture sheet colours, for example, the character's eyes are blue instead of white and the eye texture isn't there, but it does appear when you put on "Always show first texture". Another issue is that the hair colour should be red, and not black, although the texture shows up black, it's shown as red in the game. His jacket is green instead of red, and there's shading on his top that shouldn't be there, including the bottom of his jeans.

Here's a screenshot for comparison.

![image](https://i.gyazo.com/9f5242ae711966b57d79e8d41be3f4ab.png)

**Comment by Blayer98** [comment]
Also, with another version of the character, there's no shading on the top which is good, but the jacket is still green, and the skin texture appears green, which is really odd.

![image](https://cloud.githubusercontent.com/assets/6663677/13269674/dd231412-da80-11e5-90f3-f1080ab46da0.png)

**Comment by Blayer98** [comment]
![image](https://cloud.githubusercontent.com/assets/6663677/13269727/3c92a638-da81-11e5-9e5a-c1a70e7b9a72.png)
![image](https://cloud.githubusercontent.com/assets/6663677/13269733/452d778c-da81-11e5-8890-ce7eba5e046e.png)

Fragment Shader makes the textures even worse... :(
Well, at least the hair isn't black. :)

**Comment by Blayer98** [comment]
Oh, this also happens with another and quite a few characters.
![image](https://cloud.githubusercontent.com/assets/6663677/13270589/0e3f70b2-da87-11e5-8996-a4fbf6cfeb90.png)

There's green all over the texures which make them look terrible.
That green is NOT on any texture sheet.

**Comment by gdkchan** [comment]
The Detective Pikachu issue... Well, those colors are actually diffuse vertex colors, and not part of the texture (that's why you see them even if you remove all textures). The game have custom texture blending stages to blend those colors and textures together, to create different effects on the 3DS GPU. It can use up to 6 stages, and combine colors from texture 1/2/3, vertex color, shading and more. Those weird vertex colors are probably used as input on the fragment shader stage to create some neat effect, but on Ohana3DS this doesn't happens.

Heres what happens on Ohana3DS: It completely ignores all those blending stages and commands. It will use the first texture "texture 1" (when Always use first texture is selected), or use the lastest available texture if "Use last texture when present" is selected. For examble, if you have just 1 texture, it would be texture 1, if you have two, if would be texture 2 and so on. The vertex diffuse color is used straight aswell, I think that DX multiplies the vertex color with the texture color by default.

On a attempt to simulate what is done on the 3ds GPU, and getting more accurate views, I wrote a Fragment Shader to blend the textures/colors like the 3ds does. It is still incomplete, but works on most cases from what I saw. Unfortunately, it just doesn't work on most GPUs. I don't know why but I think that Managed DX is to blame. On your case, the fragment shader wasn't executed, that's why the textures disappeared for you when you enabled it.

If your intention is exporting the model, there isn't much I can do to make it come out right. Without a fragment shader, there isn't any way to make it exactly like it shows on the 3ds. But a easy solution when exporting is deleting all vertex colors on your 3D software, it will probably look OK if you do that.

**Comment by Blayer98** [comment]
Oh, interesting. Where exactly would I find the vertex shaders? Do you know what they would be referenced as?

**Comment by gdkchan** [comment]
Not sure about what you mean, but the fragment shader stuff is inside the bch itself. It's right after the strings table.

If you're asking about the fragment shader I wrote for Ohana3ds, it's inside "Ohana3DS Rebirth\Resources\OFragmentShader.txt".

**Comment by Blayer98** [comment]
Ah, sorry! I wasn't clear enough... I meant the vertex colours which you could remove with a 3D software apparently. I'm using Blender, so it's probably more difficult. :P

Why does Ohana3DS not use the shader commands? And when using the Fragment Shader, exporting shows the same blue covered texture less model, which can't be helped I guess.

**Comment by gdkchan** [comment]
It does not use the shader commands, because your GPU isn't a 3DS GPU basically. They works differently. The only way to make the PC GPU behave similar to the 3DS GPU is with a fragment shader program like I said before.

About the color issue, just export your model as SMD format (SMD doesn't support vertex colors, so they will be discaded), after you export it as *.smd, you can use the Noesis tool to convert it to any format you want (such as *.fbx or *.dae).

**Comment by Blayer98** [comment]
Oh cool! Although, will .smd keep the armatures? Since I'd like to animate without having to go through the trouble of re-constructing the bones again.

**Comment by gdkchan** [comment]
yes, it will keep the skeleton and the rigging...

**Comment by Demonslayerx8** [comment]
That model loads almost perfectly for me with fragment shader enabled, cause pretty much i have a AMD GPU, and everything nintendo (consols and their shaders) run on a AMD GPU, but ya, SMD does keep the skeleton and rigging.

![dp tim](https://cloud.githubusercontent.com/assets/17195757/13273892/bae68160-da5b-11e5-9867-adbda25b33a5.png)

**Comment by Blayer98** [comment]
Oh ok, how come yours is black? And the textures on your side don't seem to be visible...

**Comment by Demonslayerx8** [comment]
oh they're pretty visable to me, plus my pic was of the higher poly model of Tim, but here's a pic of the lower poly version
![dp tim2](https://cloud.githubusercontent.com/assets/17195757/13274217/98b2e36a-da5e-11e5-80e5-31add71009e3.png)

**Comment by Blayer98** [comment]
Hmm, I've also noticed the textures are misplaced on both high and middle models :/

![image](https://cloud.githubusercontent.com/assets/6663677/13281081/9f355422-dad9-11e5-85cf-4a4b05d4a6c1.png)

![image](https://cloud.githubusercontent.com/assets/6663677/13281186/348de2e6-dada-11e5-810e-30d8d3963536.png)

not sure what's causing it...

**Comment by Demonslayerx8** [comment]
That's normal, that just means that the materials needs to have the textures set to Mirror

as for the eyes, idk bout that, i didnt bother fixing them on my end.

**Comment by Blayer98** [comment]
Yeah, I fixed most of them with Flip UVs. :P

**Comment by Blayer98** [comment]
Dixed most UV mapping apart from the head and hair textures, which I'm not sure why it does that...

**Comment by Blayer98** [comment]
Oh interesting, both are having issues with the hair texture... You have to use the last texture when present to fix the hair, and I'm not sure about the right eye being black/alpha when that should be his skin :P

![image](https://cloud.githubusercontent.com/assets/6663677/13281476/f7ab3232-dadb-11e5-9776-5784e863d233.png)

**Comment by Demonslayerx8** [comment]
Cause nintendo models like using either Clamp or Mirror for their uv's.. i guess it save filespace or something like that :/

**Comment by Blayer98** [comment]
The 3DS has low VRAM apparently, so maybe that's it.

**Comment by Demonslayerx8** [comment]
naaah, they used that setting ever since the N64 days, even up to the WiiU, they used the same thing.

**Comment by Blayer98** [comment]
ahh ,ok.

Oh wow...
Exporting with Noesis doesn't capture the textures for some reason, so Meterials will appear as black, and textures will appear as white... :/

![image](https://cloud.githubusercontent.com/assets/6663677/13282199/b68675b0-dadf-11e5-9ae4-0ed624e88007.png)

![image](https://cloud.githubusercontent.com/assets/6663677/13282207/bbab3b34-dadf-11e5-8ad6-9b0a316e9be6.png)

**Comment by robotortoise** [comment]
This seems to be related to [this issue.](https://github.com/gdkchan/Ohana3DS-Rebirth/issues/19)

I'm getting the same textures-not-being-mapped when exporting-as-external model issue as well as you are.

I'm on an Nvidia graphics card. I assume that's the problem, as it seems other people with Nvidia GPUs are having similar issues.

Maybe it's something to do with how Nividia drivers interact with the software vs. how AMD drivers work? Or not? I don't know, I'm not a coder.


Anyways, would you like me to close my issue, as this seems to be related?

**Comment by Blayer98** [comment]
Sorry for bumping an old post here, but how would I find the strings table and remove the shader effects? Sorry, I'm not an expert coder, so I don't know what needs to be done, especially since I don't mod 3DS models...
