### ISSUE TITLE
Error with Fragment Shader???

### ISSUE THREAD

**Issue by Blayer98** [gdkchan/Ohana3DS-Rebirth#23]
Ohana3DS shows this without the fragment shader:

![image](https://cloud.githubusercontent.com/assets/6663677/13405471/6f2767b6-df16-11e5-80e4-720c3f98b62a.png)

Ohana3DS shows this with the fragment shader:

![image](https://cloud.githubusercontent.com/assets/6663677/13406111/b80e3a38-df19-11e5-8bf3-7f5504b42ce1.png)

This is what Blender shows when exporting the model as .DAE.

![image](https://cloud.githubusercontent.com/assets/6663677/13405448/59f38b90-df16-11e5-818a-e760c8465bfa.png)

(I already know about the vertex colours :P)

It appears Ohana3DS is exporting the file with the fragment shader on, even if it's disabled. Not sure what's going on here? :S

**Comment by gdkchan** [comment]
Like I said on the other issue, the Fragment Shader doesn't work for you, you "with fragment shader" picture is actually the texture-less model. And those colors you're seeing, those are vertex colors, they are USED by the fragment shader to create a different effect, but it's not really a PART of the fragment shader. Models uses vertex colors for different purpose, like creating static shading effects. On this game in particular, they use it as input for the fragment shader to create some effect... DAE is the only format on o3ds that supports said vertex colors, that's why you see them only with DAE and in no other format. The solution would be deleting the vertex color nodes, how you do that in blender I don't know as I'm not a 3D artist and I only use those 3D softwares to test if the exported files are working.

**Comment by Fallenleader** [comment]
@gdkchan don't feel bad. I'm having to learn EVERYTHING from coding to modeling to animations by myself since no one wants to help my project :P

This should help explain the extensive and annoying bug testing and animation questions XD
